name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3
      - name: "Build Image"
        run: docker image build --tag=cowsay:latest ./docker-git/
      - name: "say hello"
        run: docker container run --rm cowsay:latest bash -c "cat /README.md | /usr/games/cowsay"
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

